#!/usr/bin/python3
# -*-Python-*-

# The MIT License (MIT)
#
# Copyright (c) 2021 Dave Astels
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import os
import platform
import argparse
import glob
import json
import re
from deploy_config import config


if os.path.exists(os.path.join(os.getcwd(), "deploy_config.json")):
        with open("deploy_config.json") as f:
                overrides  = json.loads(f.read())
                for k, v in overrides.items():
                    config[k] = v


# Process the command line
parser = argparse.ArgumentParser(description="Deploy/update a CircuitPython project.")
parser.add_argument(
    "-d", "--dir", default=config["dir"], help="location of CircuitPython files"
)
parser.add_argument(
    "-v", "--version", default=config["version"], help="version of CircuitPython to use"
)
parser.add_argument(
    "-c",
    "--circuitpy",
    default=config["circuitpy"],
    help="location of the CIRCUITPY drive",
)
parser.add_argument(
    "-f", "--file", default="", help="the single file to copy to CIRCUITPY/code.py"
)
parser.add_argument(
    "-s",
    "--subdirs",
    action="store_true",
    help="copy top level subdirectories (e.g. sounds or fonts)",
)
parser.add_argument(
    "-l",
    "--updatelibs",
    action="store_true",
    help="update library modules (requires a project manifext.json)",
)

args = parser.parse_args()

manifest = None

# Find the latest bundle
bundles = glob.glob(os.path.join(args.dir, args.version, "*-bundle-*"))
bundles.sort()
bundle_name = bundles[-1]

# Create lib paths
lib_dir = os.path.join(bundle_name, "lib")
cp_lib_dir = os.path.join(args.circuitpy, "lib")


def copy_lib(lib_name):
    print("  " + lib_name)
    if (platform.system == 'Darwin'):
        cpCmd = 'cp -RX'
    elif (platform.system == 'Windows'):
        cpCmd = 'xcopy /S /Y /F'
    else:
        cpCmd = 'cp -R'
    os.system("{0} {1} {2}".format(cpCmd, os.path.join(lib_dir, lib_name), cp_lib_dir))


def included(fname):
    if fname == "manifest.json":
        return False
    if manifest is None:
        return True
    if manifest.get("exclude") is None:
        return True
    return True not in list(
        [re.fullmatch(ex, fname) is not None for ex in manifest["exclude"]]
    )


def cleanup_obsolete_code_file(fname):
    code_path = os.path.join(args.circuitpy, "code.py")
    if fname == "main.py" and os.path.exists(code_path):
        print("main.py detected, removing code.py")
        os.system("rm {0}".format(code_path))
    main_path = os.path.join(args.circuitpy, "main.py")
    if fname == "code.py" and os.path.exists(main_path):
        print("code.py detected, removing main.py")
        os.system("rm {0}".format(main_path))


def replace_file(fname):
    if included(fname):
        dest_path = os.path.join(args.circuitpy, fname)
        cleanup_obsolete_code_file(fname)
        if not os.path.isdir(fname) or args.subdirs:
            print("  " + fname)
            if os.path.exists(dest_path):
                if (platform.system == 'Windows'):
                    os.system("del /s /q {0}".format(dest_path))
                else:
                    os.system("rm -r {0}".format(dest_path))
            if (platform.system == 'Darwin'):
                cpCmd = 'cp -RX'
            elif (platform.system == 'Windows'):
                cpCmd = 'xcopy /S /Y /F'
            else:
                cpCmd = 'cp -R'
            os.system("{0} {1} {2}".format(cpCmd, fname, args.circuitpy))
    else:
        print("--" + fname)


# Update libraries
try:
    with open("manifest.json") as f:
        manifest = json.loads(f.read())
except IOError:
    print("No manifest.json, skipping library update")

if manifest and args.updatelibs:
    print("Removing old libraries")
    if not os.path.exists(cp_lib_dir):
        print("Creating " + cp_lib_dir)
        os.mkdir(cp_lib_dir)
    os.system("rm -rf {0}".format(os.path.join(cp_lib_dir, "*")))
    print("Copying new libraries from {0}".format(lib_dir))
    for lib in manifest["libs"]:
        copy_lib(lib)

# Copy project files
if args.file == "":
    print("replacing top level files/directories")
    for f in glob.glob("*"):
        replace_file(f)
else:
    code_file = args.file
    if not code_file.endswith(".py"):
        code_file += ".py"
    print("Copy {0} to code.py".format(code_file))
    if (platform.system == 'Darwin'):
        cpCmd = 'cp -RX'
    elif (platform.system == 'Windows'):
        cpCmd = 'xcopy /S /Y /F'
    else:
        cpCmd = 'cp -R'
    os.system("{0} {1} {2}".format(cpCmd, code_file, os.path.join(args.circuitpy, "code.py")))

os.system("sync")